In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [66]:
df = pd.read_csv('/content/Titanic-Dataset.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [68]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [9]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [26]:
df.groupby('Sex')['Age'].mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [69]:
df['Age'] = df.apply(
    lambda row: df.groupby('Sex')['Age'].mean()[row['Sex']] if pd.isnull(row['Age']) else row['Age'],
    axis=1
)

In [70]:
df.drop('PassengerId',axis=1,inplace=True)

In [71]:
df.drop('Name',axis=1,inplace=True)

In [37]:
df['Ticket'].nunique()

681

In [72]:
df.drop('Ticket',axis=1,inplace=True)

In [73]:
df.groupby('Cabin')['Survived'].sum()

Cabin
A10    0
A14    0
A16    1
A19    0
A20    1
      ..
F33    3
F38    0
F4     2
G6     2
T      0
Name: Survived, Length: 147, dtype: int64

In [74]:
df.drop('Cabin',axis=1,inplace=True)

In [47]:
df['Embarked'].nunique()

3

In [158]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X = df[:].values
X[:,2] = le.fit_transform(X[:,2])
X

array([[0, 3, 1, ..., 0, 7.25, 'S'],
       [1, 1, 0, ..., 0, 71.2833, 'C'],
       [1, 3, 0, ..., 0, 7.925, 'S'],
       ...,
       [0, 3, 0, ..., 2, 23.45, 'S'],
       [1, 1, 1, ..., 0, 30.0, 'C'],
       [0, 3, 1, ..., 0, 7.75, 'Q']], dtype=object)

In [159]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

array([[0.0, 0.0, 1.0, 0, 1, 22.0, 1, 0, 7.25, 'S'],
       [1.0, 0.0, 0.0, 1, 0, 38.0, 1, 0, 71.2833, 'C'],
       [0.0, 0.0, 1.0, 1, 0, 26.0, 0, 0, 7.925, 'S'],
       [1.0, 0.0, 0.0, 1, 0, 35.0, 1, 0, 53.1, 'S'],
       [0.0, 0.0, 1.0, 0, 1, 35.0, 0, 0, 8.05, 'S']], dtype=object)

In [160]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [161]:
X[0:5]

array([[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0, 1, 22.0, 1, 0, 7.25],
       [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1, 0, 38.0, 1, 0, 71.2833],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1, 0, 26.0, 0, 0, 7.925],
       [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1, 0, 35.0, 1, 0, 53.1],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0, 1, 35.0, 0, 0, 8.05]],
      dtype=object)

In [162]:
y = X[:,6]
y=y.astype('int')
X = np.delete(X,6,axis=1)
y=pd.Series(y)
X=pd.DataFrame(X)

In [163]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state = 42)

In [164]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [166]:
pred = LR.predict(X_test)

In [169]:
result = pd.DataFrame({'Real':y_test,'Predictions':pred})
result

Real  Predictions
709     1            1
439     0            0
840     1            1
720     0            0
39      1            1
..    ...          ...
821     1            1
633     0            0
456     0            0
500     1            1
430     0            0

[268 rows x 2 columns]

In [170]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
cm = confusion_matrix(y_test,pred)
cf = classification_report(y_test,pred)
print(cm)
print(cf)

[[129   0]
 [  0 139]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       129
           1       1.00      1.00      1.00       139

    accuracy                           1.00       268
   macro avg       1.00      1.00      1.00       268
weighted avg       1.00      1.00      1.00       268

